
#LOG "- Adding 1.3 meta Vulkan blobs"
#ADD_TO_WORK_DIR "A837" "vendor" "lib64" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "lib" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "lib64/hw" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "lib/hw" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "lib64/egl" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "lib/egl" 0 0 755 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "etc/permissions/android.hardware.vulkan.version-1_3.xml" 0 0 644 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "etc/permissions/android.software.opengles.deqp.level.xml" 0 0 644 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "etc/permissions/android.software.vulkan.deqp.level.xml" 0 0 644 "u:object_r:vendor_file:s0"
#ADD_TO_WORK_DIR "A837" "vendor" "etc/permissions/android.hardware.opengles.aep.xml" 0 0 644 "u:object_r:vendor_file:s0"

LOG " - Enabling vulkan"
SET_PROP "vendor" "ro.hwui.use_vulkan" "true"
SET_PROP "vendor" "debug.hwui.use_hint_manager" "true"
SET_PROP "system" "debug.hwui.renderer" "skiavk"
SET_PROP "system" "debug.hwui.skip_empty_frames" "1"
SET_PROP "system" "ro.hwui.use_vulkan" "true"
SET_PROP "system" "graphics.gpu.profiler.support" "true"
SET_PROP "system" "ro.opengles.version" "196610"
